# A docker-compose must always start by the version tag.
# We use "3" because it's the last version at this time.
version: "3"

services:

  server:
    build: server/
    command: python ./server.py
    ports:
      - 1234:1234

  client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server


  mongo:
    image: mongo:latest
    build: mongodb/
    command: python3 ./mongo.py
    network_mode: host
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo:
