version: '3.1'

services:
  mongo:
    image: schedulerContainer.azurecr.io/mongo
    restart: always
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: --quiet

  mongo-express:
    image: schedulerContainer.azurecr.io/mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - "mongo"

  init:
    image: schedulerContainer.azurecr.io/init
    build: init
    command: python ./init.py
          
  master:
    image: master
    build: master
    restart: always
    command: python -u ./master.py
    environment: 
      PYTHONUNBUFFERED: 1
    ports:
      - 2345:2345
    depends_on: 
      - init

  slave:
    image: schedulerContainer.azurecr.io/slave
    build: slave
    command: python ./slave.py
    links:
      - "master"
    depends_on: 
      - master