version: '3.1'

services:
  master:
    build: master/
    command: python ./init.py
    command: python ./master.py
    ports:
      - 1234:1234

  slave:
    build: slave/
    command: python ./slave.py
    ports:
      - 1234:1234
    depends_on: 
      master
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example